export const template = `<article class="card vault-card contacts-card"><span class="eyebrow">CONEXÕES SOB SEU CONTROLE</span><h2>Seus contatos</h2>
<p>Salvar uma wallet guarda um apelido na sua agenda. Solicitar conversa e aceitar são escolhas separadas. Apelidos ficam cifrados; o servidor aplica as permissões.</p><p data-contact-status role="status">Conecte e autorize o aparelho para sincronizar.</p>
<div data-contact-invite-peer></div><button data-contact-action="refresh" type="button" hidden>Tentar novamente</button>
<form data-book-form><h3 data-book-title>Salvar wallet na agenda</h3><label>Ecossistema<select data-book-network><option value="evm">EVM</option><option value="solana">Solana</option></select></label><label>Endereço completo da wallet<input data-book-address required maxlength="44" autocomplete="off" spellcheck="false"></label><label>Apelido particular<input data-book-alias maxlength="80" autocomplete="off"></label><button type="submit" class="primary">Salvar contato</button><button data-contact-action="new" type="button">Novo contato</button><button data-contact-action="discover" type="button">Pedir conversa</button><button data-contact-action="block-wallet" type="button">Bloquear esta wallet</button></form>
<p data-contact-discovery></p><div data-contact-discovery-actions></div><p class="detail">Indisponível pode significar wallet não cadastrada, privacidade, aparelho ainda não autorizado ou bloqueio. Você pode salvar a wallet e compartilhar seu próprio convite manualmente.</p>
<label>Buscar apelido nesta agenda<input data-book-search type="search" maxlength="80" autocomplete="off"></label><p data-book-state></p><ul data-book-list class="vault-list"></ul><button data-contact-action="book-more" type="button">Próxima página da agenda</button>
<h3>Solicitações recebidas</h3><ul data-contact-list="incoming" class="vault-list"></ul><button data-contact-page="incoming" type="button">Próxima página de recebidas</button>
<h3>Solicitações enviadas</h3><ul data-contact-list="outgoing" class="vault-list"></ul><button data-contact-page="outgoing" type="button">Próxima página de enviadas</button>
<h3>Contatos aprovados</h3><ul data-contact-list="approved" class="vault-list"></ul><button data-contact-page="approved" type="button">Próxima página de aprovados</button>
<h3>Solicitações rejeitadas</h3><ul data-contact-list="rejected" class="vault-list"></ul><button data-contact-page="rejected" type="button">Próxima página de rejeitadas</button>
<h3>Bloqueios atuais</h3><ul data-contact-list="blocked" class="vault-list"></ul><button data-contact-page="blocked" type="button">Próxima página de bloqueios</button>
<p class="detail">Bloqueio vale para esta identidade, não para outras wallets da mesma pessoa. Desbloquear não restaura aprovação nem apaga cópias antigas. Novos envios são impedidos e entregas pendentes ficam suspensas até novo consentimento.</p></article>`;

export const settingsTemplate = `<article class="card"><h2>Contatos e convites</h2><p data-contact-status role="status"></p><h3>Quem pode me encontrar e solicitar?</h3><form data-contact-settings><label>Descoberta<select data-contact-mode><option value="invite">Somente com meu link de convite</option><option value="wallet">Por wallet exata ou convite</option><option value="contacts">Somente contatos já aprovados</option></select></label><p>Você escolhe: somente convite ou também busca pelo endereço exato da wallet. Ser encontrado permite solicitar; conversar depende do seu aceite. Não existe diretório público nem busca por nomes. O nome que você escolheu aparece nas solicitações. Fotos e presença não aparecem para desconhecidos.</p><button type="submit" class="primary">Aplicar visibilidade</button></form>
<button data-contact-action="rotate" type="button">Criar / trocar meu convite</button><button data-contact-action="revoke" type="button">Revogar meu convite</button><div data-contact-own-invite hidden><label>Meu link de convite<input data-contact-invite readonly spellcheck="false"></label><div data-contact-invite-qr class="device-qr"></div><button data-contact-action="copy" type="button">Copiar link</button><p data-contact-invite-state>Compartilhe somente com quem pode solicitar contato. O link não autoriza aparelho nem aprova conversa.</p></div>
<form data-contact-invite-form><h3>Recebi um convite</h3><label>Link de convite<input data-contact-received type="url" maxlength="512" required autocomplete="off" spellcheck="false"></label><button type="submit">Solicitar conversa</button><button data-contact-action="scan" type="button">Ler QR pela câmera</button><button data-contact-action="stop-camera" type="button" hidden>Encerrar câmera</button><video data-contact-camera hidden muted playsinline></video></form>
<div data-contact-invite-peer></div><p>O app valida o convite automaticamente. A conversa começa depois do aceite do destinatário.</p>
</article>`;
