export const template = `<article class="card vault-card contacts-card"><span class="eyebrow">CONEXÕES SOB SEU CONTROLE</span><h2>Agenda particular e consentimento.</h2>
<p>Salvar uma wallet preserva seu contato privado. Solicitar conversa e aceitar são escolhas separadas. Apelidos ficam cifrados; o servidor aplica as permissões.</p><p data-contact-status role="status">Conecte e autorize o aparelho para sincronizar.</p>
<button data-contact-action="refresh" class="primary" type="button">Abrir / atualizar contatos</button><button data-contact-action="local" type="button">Abrir somente agenda local</button><a href="#cofre">Gerenciar cofre e envios incompletos</a>
<form data-book-form><h3 data-book-title>Salvar wallet na agenda</h3><label>Ecossistema<select data-book-network><option value="evm">EVM</option><option value="solana">Solana</option></select></label><label>Endereço completo da wallet<input data-book-address required maxlength="44" autocomplete="off" spellcheck="false"></label><label>Apelido particular<input data-book-alias maxlength="80" autocomplete="off"></label><button type="submit" class="primary">Salvar contato privado</button><button data-contact-action="new" type="button">Novo contato</button><button data-contact-action="discover" type="button">Consultar esta wallet</button><button data-contact-action="block-wallet" type="button">Bloquear esta wallet</button></form>
<p data-contact-discovery></p><div data-contact-discovery-actions></div><p class="detail">Indisponível pode significar wallet não cadastrada, privacidade, aparelho ainda não autorizado ou bloqueio. Você pode salvar a wallet e compartilhar seu próprio convite manualmente.</p>
<label>Buscar apelido nesta agenda<input data-book-search type="search" maxlength="80" autocomplete="off"></label><p data-book-state></p><ul data-book-list class="vault-list"></ul><button data-contact-action="book-more" type="button">Próxima página da agenda</button><button data-contact-action="book-load" type="button">Carregar mais índice do cofre</button>
<button data-contact-action="own-identity" type="button">Mostrar minha identidade</button><div data-contact-own-identity hidden><h3>Minha identidade pública</h3><p data-contact-own-fingerprint class="recovery-message"></p><div data-contact-own-identity-qr class="device-qr"></div><p>Mostre este código ao contato por um canal independente. Ele deve comparar com a identidade que aparece nos seus detalhes. Este código público não autoriza aparelhos nem abre dados cifrados.</p></div>
<div data-contact-identity hidden><h3>Identidade criptográfica</h3><p data-contact-fingerprint class="recovery-message"></p><div data-contact-identity-qr class="device-qr"></div><p>Peça à pessoa que abra “Mostrar minha identidade” e compare este código por um canal independente. A primeira referência vem do servidor; uma assinatura válida não comprova identidade civil. Novas mudanças precisam manter esta cadeia.</p><button data-contact-action="pin" type="button">Guardar referência verificada na agenda</button></div>
<h3>Quem pode me encontrar e solicitar?</h3><form data-contact-settings><label>Descoberta<select data-contact-mode><option value="invite">Somente com meu link de convite</option><option value="wallet">Quem conhece minha wallet exata</option><option value="contacts">Somente contatos já aprovados</option></select></label><p>Não existe diretório público nem busca por nomes. O nome que você escolheu aparece nas solicitações. Fotos e presença não aparecem para desconhecidos.</p><button type="submit" class="primary">Aplicar visibilidade</button></form>
<button data-contact-action="rotate" type="button">Criar / trocar meu convite</button><button data-contact-action="revoke" type="button">Revogar meu convite</button><div data-contact-own-invite hidden><label>Meu link de convite<input data-contact-invite readonly spellcheck="false"></label><div data-contact-invite-qr class="device-qr"></div><button data-contact-action="copy" type="button">Copiar link</button><p data-contact-invite-state>Compartilhe somente com quem pode solicitar contato. O link não autoriza aparelho nem aprova conversa.</p></div>
<form data-contact-invite-form><h3>Recebi um convite</h3><label>Link de convite<input data-contact-received type="url" maxlength="512" required autocomplete="off" spellcheck="false"></label><button type="submit">Conferir convite</button><button data-contact-action="scan" type="button">Ler QR pela câmera</button><button data-contact-action="stop-camera" type="button">Encerrar câmera</button><video data-contact-camera hidden muted playsinline></video></form>
<div data-contact-invite-peer></div><p>Conferir não envia solicitação. Depois de conferir a wallet e o ecossistema, escolha solicitar explicitamente.</p>
<h3>Solicitações recebidas</h3><ul data-contact-list="incoming" class="vault-list"></ul><button data-contact-page="incoming" type="button">Próxima página de recebidas</button>
<h3>Solicitações enviadas</h3><ul data-contact-list="outgoing" class="vault-list"></ul><button data-contact-page="outgoing" type="button">Próxima página de enviadas</button>
<h3>Contatos aprovados</h3><ul data-contact-list="approved" class="vault-list"></ul><button data-contact-page="approved" type="button">Próxima página de aprovados</button>
<h3>Solicitações rejeitadas</h3><ul data-contact-list="rejected" class="vault-list"></ul><button data-contact-page="rejected" type="button">Próxima página de rejeitadas</button>
<h3>Bloqueios atuais</h3><ul data-contact-list="blocked" class="vault-list"></ul><button data-contact-page="blocked" type="button">Próxima página de bloqueios</button>
<p class="detail">Até 64 solicitações recebidas e 32 enviadas pendentes; 32 novas por dia UTC. Até 256 relações e 256 bloqueios por conta. Bloqueio vale para esta identidade, não para outras wallets da mesma pessoa. Desbloquear não restaura aprovação nem apaga cópias antigas. Mensagens serão habilitadas no bloco seguinte.</p></article>`;
