import { chatIcon } from '../chat-ui/index.ts';

const inviteForm = `<form data-contact-invite-form><label>Link de convite<input data-contact-received type="url" maxlength="512" required autocomplete="off" spellcheck="false" placeholder="Cole o link do 0xDMme"></label><p class="contact-hint">O convite permite pedir uma conversa. O destinatário precisa aceitar.</p><div class="contact-form-actions"><button type="submit" class="primary">Solicitar conversa</button><button data-contact-action="scan" type="button">Ler QR</button><button data-contact-action="stop-camera" type="button" hidden>Encerrar câmera</button></div><video data-contact-camera hidden muted playsinline></video></form>`;

export const template = `<article class="card contacts-card">
<header class="contacts-heading"><div><h1>Contatos</h1><p>Sua agenda e pedidos de conversa.</p></div><button data-contact-add class="primary" type="button"><span aria-hidden="true">＋</span> Adicionar contato</button></header>
<div class="contacts-toolbar"><label class="contact-search"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10" cy="10" r="7"/><path d="m15 15 6 6"/></svg><input data-book-search type="search" maxlength="80" autocomplete="off" aria-label="Buscar nesta lista" placeholder="Buscar nesta lista…"></label><a class="contact-invite-link" href="#perfil">Meu convite ↗</a></div>
<div class="contact-tabs" role="tablist" aria-label="Listas de contatos">
<button data-contact-tab="main" data-tab="approved" role="tab" id="contacts-tab-approved" aria-controls="contacts-panel-approved" aria-selected="true" type="button">Contatos</button>
<button data-contact-tab="main" data-tab="requests" role="tab" id="contacts-tab-requests" aria-controls="contacts-panel-requests" aria-selected="false" tabindex="-1" type="button">Solicitações <span data-contact-request-count class="contact-count" hidden></span></button>
<button data-contact-tab="main" data-tab="agenda" role="tab" id="contacts-tab-agenda" aria-controls="contacts-panel-agenda" aria-selected="false" tabindex="-1" type="button">Agenda</button>
<button data-contact-tab="main" data-tab="blocked" role="tab" id="contacts-tab-blocked" aria-controls="contacts-panel-blocked" aria-selected="false" tabindex="-1" type="button">Bloqueados</button></div>
<section data-contact-panel="main" data-tab="approved" id="contacts-panel-approved" role="tabpanel" aria-labelledby="contacts-tab-approved"><div class="contact-section-heading"><h2>Conversas liberadas</h2><span data-contact-page-state="approved"></span></div><ul data-contact-list="approved" class="contact-list"></ul><button data-contact-page="approved" class="contact-more" type="button" hidden>Próxima página</button></section>
<section data-contact-panel="main" data-tab="requests" id="contacts-panel-requests" role="tabpanel" aria-labelledby="contacts-tab-requests" hidden><div class="contact-subtabs" role="tablist" aria-label="Solicitações"><button data-contact-tab="requests" data-tab="incoming" role="tab" id="contacts-tab-incoming" aria-controls="contacts-panel-incoming" aria-selected="true" type="button">Recebidas</button><button data-contact-tab="requests" data-tab="outgoing" role="tab" id="contacts-tab-outgoing" aria-controls="contacts-panel-outgoing" aria-selected="false" tabindex="-1" type="button">Enviadas</button><button data-contact-tab="requests" data-tab="rejected" role="tab" id="contacts-tab-rejected" aria-controls="contacts-panel-rejected" aria-selected="false" tabindex="-1" type="button">Recusadas</button></div>
<section data-contact-panel="requests" data-tab="incoming" id="contacts-panel-incoming" role="tabpanel" aria-labelledby="contacts-tab-incoming"><p class="contact-hint">Você decide quem pode conversar com você.</p><ul data-contact-list="incoming" class="contact-list"></ul><button data-contact-page="incoming" class="contact-more" type="button" hidden>Próxima página</button></section>
<section data-contact-panel="requests" data-tab="outgoing" id="contacts-panel-outgoing" role="tabpanel" aria-labelledby="contacts-tab-outgoing" hidden><p class="contact-hint">Aguardando o aceite do destinatário.</p><ul data-contact-list="outgoing" class="contact-list"></ul><button data-contact-page="outgoing" class="contact-more" type="button" hidden>Próxima página</button></section>
<section data-contact-panel="requests" data-tab="rejected" id="contacts-panel-rejected" role="tabpanel" aria-labelledby="contacts-tab-rejected" hidden><ul data-contact-list="rejected" class="contact-list"></ul><button data-contact-page="rejected" class="contact-more" type="button" hidden>Próxima página</button></section></section>
<section data-contact-panel="main" data-tab="agenda" id="contacts-panel-agenda" role="tabpanel" aria-labelledby="contacts-tab-agenda" hidden><div class="contact-section-heading"><h2>Agenda particular</h2><span data-book-state></span></div><p class="contact-hint">Salvar um contato não libera a conversa. Abra um registro para editar ou conferir versões.</p><ul data-book-list class="contact-list"></ul><button data-contact-action="book-more" class="contact-more" type="button" hidden>Próxima página</button></section>
<section data-contact-panel="main" data-tab="blocked" id="contacts-panel-blocked" role="tabpanel" aria-labelledby="contacts-tab-blocked" hidden><div class="contact-section-heading"><h2>Bloqueios</h2></div><p class="contact-hint">Desbloquear exige novo aceite para conversar. O bloqueio vale para essa identidade.</p><ul data-contact-list="blocked" class="contact-list"></ul><button data-contact-page="blocked" class="contact-more" type="button" hidden>Próxima página</button></section>
<div class="contact-feedback"><p data-contact-status role="status"></p><button data-contact-action="refresh" type="button" hidden>Tentar novamente</button></div><p class="contact-test-note">Chat em teste · use somente dados fictícios. Busca nos itens carregados neste aparelho.</p>
<dialog data-contact-editor class="contact-dialog" aria-labelledby="contact-editor-title"><header><div><span class="contact-eyebrow">SUA AGENDA</span><h2 id="contact-editor-title" data-book-title>Adicionar contato</h2></div><button data-contact-editor-close class="contact-close" type="button" aria-label="Fechar formulário">${chatIcon('close')}</button></header>
<div class="contact-subtabs" role="tablist" aria-label="Como adicionar contato"><button data-contact-tab="editor" data-tab="wallet" role="tab" id="contact-tab-wallet" aria-controls="contact-panel-wallet" aria-selected="true" type="button">Por wallet</button><button data-contact-tab="editor" data-tab="invite" role="tab" id="contact-tab-invite" aria-controls="contact-panel-invite" aria-selected="false" tabindex="-1" type="button">Por convite</button></div>
<section data-contact-panel="editor" data-tab="wallet" id="contact-panel-wallet" role="tabpanel" aria-labelledby="contact-tab-wallet"><form data-book-form><label>Ecossistema<select data-book-network><option value="evm">EVM</option><option value="solana">Solana</option></select></label><label>Endereço completo da wallet<input data-book-address required maxlength="44" autocomplete="off" spellcheck="false" placeholder="0x… ou endereço Solana"></label><label><span>Apelido particular <small class="contact-optional">opcional</small></span><input data-book-alias maxlength="80" autocomplete="off" placeholder="Como você quer salvar este contato"></label><p class="contact-hint">Salvar na agenda não envia uma solicitação.</p><div class="contact-form-actions"><button type="submit" class="primary">Salvar contato</button><button data-contact-action="discover" type="button">Solicitar conversa</button></div></form><p data-contact-discovery class="contact-hint"></p><div data-contact-discovery-actions></div></section>
<section data-contact-panel="editor" data-tab="invite" id="contact-panel-invite" role="tabpanel" aria-labelledby="contact-tab-invite" hidden>${inviteForm}<div data-contact-invite-peer></div></section>
<div class="contact-feedback"><p data-contact-editor-status role="status"></p></div></dialog></article>`;

export const settingsTemplate = `<article class="card"><h2>Contatos e convites</h2><p data-contact-status role="status"></p><button data-contact-action="refresh" type="button" hidden>Tentar novamente</button><h3>Quem pode me encontrar e solicitar?</h3><form data-contact-settings><label>Descoberta<select data-contact-mode><option value="invite">Somente com meu link de convite</option><option value="wallet">Por wallet exata ou convite</option><option value="contacts">Somente contatos já aprovados</option></select></label><p>Você escolhe: somente convite ou também busca pelo endereço exato da wallet. Ser encontrado permite solicitar; conversar depende do seu aceite. Não existe diretório público nem busca por nomes. O nome que você escolheu aparece nas solicitações. Fotos e presença não aparecem para desconhecidos.</p><button type="submit" class="primary">Aplicar visibilidade</button></form>
<button data-contact-action="rotate" type="button">Criar / trocar meu convite</button><button data-contact-action="revoke" type="button">Revogar meu convite</button><div data-contact-own-invite hidden><label>Meu link de convite<input data-contact-invite readonly spellcheck="false"></label><div data-contact-invite-qr class="device-qr"></div><button data-contact-action="copy" type="button">Copiar link</button><p data-contact-invite-state>Compartilhe somente com quem pode solicitar contato. O link não autoriza aparelho nem aprova conversa.</p></div>
<h3>Recebi um convite</h3>${inviteForm}
<div data-contact-invite-peer></div><p>O app valida o convite automaticamente. A conversa começa depois do aceite do destinatário.</p>
</article>`;
