const decoder = new TextDecoder();
const text = (b: Uint8Array, from: number, count: number) =>
  decoder.decode(b.subarray(from, from + count));
function view(b: Uint8Array): DataView {
  return new DataView(b.buffer, b.byteOffset, b.byteLength);
}
export interface ImageShape {
  type: string;
  width: number;
  height: number;
}
function bounded(shape: ImageShape, pixels: number): ImageShape {
  if (
    !shape.width ||
    !shape.height ||
    Math.max(shape.width, shape.height) > 16384 ||
    shape.width * shape.height > pixels
  )
    throw new Error('Imagem excede o orçamento de pixels deste aparelho.');
  return shape;
}
/** Read dimensions before decoder allocation; no SVG/HTML/animated image rendering. */
export function imageShape(bytes: Uint8Array, pixels = 24_000_000): ImageShape {
  if (bytes.length < 24) throw new Error('Imagem incompleta.');
  if (text(bytes, 1, 3) === 'PNG' && bytes[0] === 137) {
    return pngShape(bytes, pixels);
  }
  if (bytes[0] === 255 && bytes[1] === 216) return jpegShape(bytes, pixels);
  if (text(bytes, 0, 4) === 'RIFF' && text(bytes, 8, 4) === 'WEBP')
    return webpShape(bytes, pixels);
  throw new Error(
    'Use foto PNG, JPEG ou WebP. Outros formatos podem ser enviados como arquivo.',
  );
}
function pngShape(bytes: Uint8Array, pixels: number): ImageShape {
  const v = view(bytes);
  if (text(bytes, 12, 4) !== 'IHDR') throw new Error('PNG inválido.');
  for (let at = 8; at + 12 <= bytes.length;) {
    const length = v.getUint32(at),
      type = text(bytes, at + 4, 4);
    if (type === 'acTL') throw new Error('Imagem animada não é uma foto.');
    if (length > bytes.length - at - 12) throw new Error('PNG truncado.');
    at += length + 12;
  }
  return bounded(
    { type: 'image/png', width: v.getUint32(16), height: v.getUint32(20) },
    pixels,
  );
}
function startsBytes(bytes: Uint8Array, prefix: number[], offset = 0): boolean {
  return prefix.every((value, index) => bytes[offset + index] === value);
}
function jpegShape(b: Uint8Array, pixels: number): ImageShape {
  const v = view(b);
  for (let at = 2; at + 4 <= b.length;) {
    if (b[at] !== 255) throw new Error('JPEG inválido.');
    const marker = b[at + 1],
      length = v.getUint16(at + 2);
    if (length < 2 || at + 2 + length > b.length)
      throw new Error('JPEG truncado.');
    if ([192, 193, 194].includes(marker ?? 0))
      return bounded(
        {
          type: 'image/jpeg',
          width: v.getUint16(at + 7),
          height: v.getUint16(at + 5),
        },
        pixels,
      );
    if (marker === 218) break;
    at += length + 2;
  }
  throw new Error('Dimensões JPEG ausentes.');
}
function webpShape(b: Uint8Array, pixels: number): ImageShape {
  const v = view(b),
    kind = text(b, 12, 4);
  if (kind === 'VP8X' && b.length >= 30) {
    if (v.getUint8(20) & 2) throw new Error('Imagem animada não é uma foto.');
    const width = 1 + (v.getUint32(23, true) >>> 8),
      height = 1 + (v.getUint32(26, true) >>> 8);
    return bounded({ type: 'image/webp', width, height }, pixels);
  }
  if (kind === 'VP8 ' && b.length >= 30 && startsBytes(b, [157, 1, 42], 23))
    return bounded(
      {
        type: 'image/webp',
        width: v.getUint16(26, true) & 16383,
        height: v.getUint16(28, true) & 16383,
      },
      pixels,
    );
  if (kind === 'VP8L' && b.length >= 25 && b[20] === 47) {
    const bits = v.getUint32(21, true);
    return bounded(
      {
        type: 'image/webp',
        width: 1 + (bits & 16383),
        height: 1 + ((bits >>> 14) & 16383),
      },
      pixels,
    );
  }
  throw new Error('WebP inválido.');
}
/** Verify the generated bytes, rather than promising metadata removal from input. */
export function metadataFree(bytes: Uint8Array, type: string): boolean {
  if (type === 'image/png') return pngMetadataFree(bytes);
  return type === 'image/jpeg' && jpegMetadataFree(bytes);
}
function pngMetadataFree(b: Uint8Array): boolean {
  const v = view(b);
  for (let at = 8; at + 12 <= b.length;) {
    if (!safePngChunks.includes(text(b, at + 4, 4))) return false;
    const size = v.getUint32(at);
    if (size > b.length - at - 12) return false;
    at += size + 12;
  }
  return true;
}
function jpegMetadataFree(b: Uint8Array): boolean {
  const v = view(b);
  for (let at = 2; at + 4 <= b.length;) {
    const marker = v.getUint8(at + 1);
    if (marker === 218) return true;
    if (marker === 254 || (marker >= 225 && marker <= 239)) return false;
    const size = v.getUint16(at + 2);
    if (size < 2 || size > b.length - at - 2) return false;
    at += size + 2;
  }
  return false;
}
export const safePngChunks = [
  'IHDR',
  'IDAT',
  'IEND',
  'sRGB',
  'gAMA',
  'cHRM',
  'PLTE',
  'tRNS',
  'pHYs',
];
