[Unit]
Requires=0xdmme-media.socket
After=0xdmme-media.socket

[Service]
Environment=HASH_TALK_MEDIA_SOCKET=/run/0xdmme-media.sock
Environment=HASH_TALK_MEDIA_FFMPEG=/opt/0xdmme-media/ffmpeg
Environment=HASH_TALK_MEDIA_FFPROBE=/opt/0xdmme-media/ffprobe
BindReadOnlyPaths=/run/0xdmme-media.sock
