import type { MediaProcessRequest } from './isolated.ts';

export function probeCommand(path: string): string[] {
  return [
    '-v',
    'error',
    '-protocol_whitelist',
    'file,pipe',
    '-format_whitelist',
    'mov,matroska,webm,gif,png_pipe,jpeg_pipe,webp_pipe',
    '-threads',
    '4',
    '-count_frames',
    '-show_entries',
    'format=format_name,duration:stream=codec_name,codec_type,width,height,duration,avg_frame_rate,nb_read_frames,nb_frames',
    '-of',
    'json',
    path,
  ];
}

type Preparation = 'photo' | 'gif' | 'video' | 'thumbnail';
const budgets: Record<Preparation, number> = {
  photo: 3_000_000,
  gif: 10_000_000,
  video: 25_000_000,
  thumbnail: 96_000,
};
export function preparationCommand(input: {
  kind: Preparation;
  source: string;
  output: string;
}): MediaProcessRequest {
  const args = [
    '-hide_banner',
    '-nostdin',
    '-v',
    'error',
    '-xerror',
    '-err_detect',
    'explode',
    '-n',
    '-filter_threads',
    '4',
    '-filter_complex_threads',
    '4',
    '-max_alloc',
    '268435456',
    '-protocol_whitelist',
    'file,pipe',
    '-format_whitelist',
    'mov,matroska,webm,gif,png_pipe,jpeg_pipe,webp_pipe',
    '-threads',
    '4',
    '-i',
    input.source,
  ];
  return {
    binary: 'ffmpeg',
    maximumBytes: budgets[input.kind],
    args: [
      ...args,
      ...preparationOptions(input.kind),
      '-fs',
      String(budgets[input.kind] + 1),
      input.output,
    ],
  };
}
function preparationOptions(kind: Preparation): string[] {
  if (kind === 'photo') return ['-map', '0:v:0', '-an', '-f', 'null'];
  if (kind === 'thumbnail')
    return [
      '-map',
      '0:v:0',
      '-an',
      '-vf',
      'scale=144:144:force_original_aspect_ratio=decrease',
      '-frames:v',
      '1',
      '-c:v',
      'png',
      '-threads',
      '1',
      '-map_metadata',
      '-1',
      '-f',
      'image2',
    ];
  if (kind === 'gif')
    return [
      '-filter_complex',
      '[0:v]fps=20,split[a][b];[a]palettegen=stats_mode=single:reserve_transparent=1[p];[b][p]paletteuse=new=1:dither=none',
      '-an',
      '-map_metadata',
      '-1',
      '-loop',
      '0',
      '-f',
      'gif',
    ];
  const scale =
    "scale=w='if(gte(iw,ih),min(1280,iw),min(720,iw))':h='if(gte(iw,ih),min(720,ih),min(1280,ih))':force_original_aspect_ratio=decrease:force_divisible_by=2";
  return [
    '-map',
    '0:v:0',
    '-map',
    '0:a:0?',
    '-vf',
    `fps=30,${scale}`,
    '-c:v',
    'libx264',
    '-threads',
    '4',
    '-preset',
    'veryfast',
    '-crf',
    '23',
    '-maxrate',
    '2800k',
    '-bufsize',
    '5600k',
    '-pix_fmt',
    'yuv420p',
    '-c:a',
    'aac',
    '-b:a',
    '128k',
    '-map_metadata',
    '-1',
    '-map_chapters',
    '-1',
    '-movflags',
    '+faststart',
    '-f',
    'mp4',
  ];
}
/** Accept only commands generated by the preparer, never arbitrary FFmpeg options. */
export function mediaCommandPaths(request: MediaProcessRequest): string[] {
  const output = request.args.at(-1);
  if (!output) throw new Error('Comando vazio.');
  if (request.binary === 'ffprobe') {
    if (
      request.maximumBytes !== 100_000_000 ||
      !sameArgs(request.args, probeCommand(output))
    )
      throw new Error('Comando de inspeção inválido.');
    return [output];
  }
  const source = request.args[request.args.indexOf('-i') + 1];
  if (!source) throw new Error('Origem ausente.');
  return preparationPaths(request, source, output);
}
function preparationPaths(
  request: MediaProcessRequest,
  source: string,
  output: string,
): string[] {
  if (!source.endsWith('/source')) throw new Error('Origem inválida.');
  for (const kind of ['photo', 'gif', 'video', 'thumbnail'] as const) {
    const expected = preparationCommand({ kind, source, output });
    if (
      request.maximumBytes === expected.maximumBytes &&
      sameArgs(request.args, expected.args)
    ) {
      return preparationOutputPaths(kind, source, output);
    }
  }
  throw new Error('Comando de preparação inválido.');
}
function preparationOutputPaths(
  kind: Preparation,
  source: string,
  output: string,
): string[] {
  if (kind === 'photo') {
    if (output !== '-') throw new Error('Saída de validação inválida.');
    return [source];
  }
  if (!output.endsWith(kind === 'thumbnail' ? '/thumbnail' : '/result'))
    throw new Error('Saída de preparação inválida.');
  return [source, output];
}
function sameArgs(actual: string[], expected: string[]): boolean {
  return (
    actual.length === expected.length &&
    actual.every((arg, i) => arg === expected[i])
  );
}
